# Generated by Django 4.2.5 on 2023-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس بنر')),
                ('Image', models.ImageField(upload_to='images/banner', verbose_name='تصویر')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزییات محصول'), ('about_us', 'درباره ما')], max_length=300, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
            },
        ),
    ]
