# Generated by Django 4.2.5 on 2023-10-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_sitebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitebanner',
            old_name='Image',
            new_name='image',
        ),
    ]
