# Generated by Django 4.2.5 on 2023-10-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_article_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
